### ISSUE TITLE
only two files or i can download and execute many files in back ground ?

### ISSUE THREAD

**Issue by pretech86** [henriksb/TrojanGenerator#1]
thanks for the programe , only two files or i can download and execute many files in back ground ?

**Comment by henriksb** [comment]
Hi, as of right now there are only two files. One file being shown and one running hidden in the background. You could have multiple files open if you compile them into one file outside of the program, but for right now the program does not do this. 
I'm glad you like the script! If you have any more questions, please ask for help and I would be happy to reply.
